"""
decision_trace.py -- per-step Decision Trace (V3 roadmap, section 6).

Every field here is read off state `runner.py`'s control loop has ALREADY
computed for this step (the observation given to the controller, the
controller's proposal, the safety-projection result, and the verified plant
state). This module adds no new computation of its own except formatting --
it builds a deterministic, reproducible, human-readable record from existing
numbers, specifically so that the record can be regenerated byte-for-byte
from the same seed and config (see test_decision_trace.py::test_determinism).

REQUIRED RULE (roadmap section 6): the physics-check status is one of
VERIFIED, INFEASIBLE, SOLVER_FAILED and must never be collapsed into a
generic success/failure flag. `build_trace` reads `res.status` directly and
raises if it sees anything else, rather than silently coercing an unknown
status into one of the three.
"""
from __future__ import annotations
from dataclasses import dataclass, asdict, field

REQUIRED_STATUSES = ('verified', 'infeasible', 'solver_failed')

# Stress thresholds used ONLY to decide what to report as "detected" -- they
# do not feed back into control or safety in any way; changing them changes
# the trace's wording, never the simulation's behaviour.
TX_STRESS_PCT = 85.0
V_STRESS_PU = 0.955


@dataclass
class DecisionTrace:
    step: int
    hour: float
    detected: str
    forecast_p10_kw: float
    forecast_p50_kw: float
    forecast_p90_kw: float
    actions: dict
    safety_status: str                 # VERIFIED | INFEASIBLE | SOLVER_FAILED, uppercase
    safety_interventions: int
    safety_scales: dict
    violations: list
    result_tx_loading_pct: float
    result_vmin_pu: float
    result_vmax_pu: float
    reason: str
    controller: str

    def to_dict(self):
        return asdict(self)


def _detect(obs, forecast, k):
    net_p50 = float(forecast['inflex']['p50'][k] - forecast['pv']['p50'][k])
    net_p90 = float(forecast['inflex']['p90'][k] - forecast['pv']['p10'][k])
    parts = []
    if net_p90 > net_p50 * 1.15 and net_p90 > 50:
        parts.append(f"forecast P90 net demand ({net_p90:.0f} kW) is well above "
                     f"P50 ({net_p50:.0f} kW): meaningful upside risk this step")
    if not parts:
        parts.append(f"no elevated stress signal (forecast P50 net demand {net_p50:.0f} kW)")
    return "; ".join(parts)


def _summarise_actions(ev_p, prot, bc, bd, fl):
    def _fmt(d, label):
        if not d:
            return None
        return f"{label}: {len(d)} resource(s), {sum(d.values()):.1f} kW total"
    out = {}
    for d, label, key in ((ev_p, 'EV charging (predicted preference)', 'ev'),
                          (prot, 'EV charging (explicit requirement)', 'protected_ev'),
                          (bc, 'battery charging', 'batt_chg'),
                          (bd, 'battery discharging', 'batt_dis'),
                          (fl, 'deferrable appliances', 'appliances')):
        s = _fmt(d, label)
        if s:
            out[key] = s
    return out


def _reason(status, n_interventions, scales, tx_loading, fallback_used):
    if status == 'solver_failed':
        return ("The verifying power flow did not converge for the final action. "
               "This step's dispatch must NOT be treated as confirmed safe; see "
               "AUDIT-STATUS.md for how solver_failed is handled upstream "
               "(every numeric field from a failed solve is NaN, not a guess).")
    if status == 'infeasible':
        base = ("No action satisfying every electrical constraint existed under "
               "the current limits and the controller's own plan.")
        if fallback_used:
            base += " The system fell back to a transparent rule policy rather than output zeros."
        return base
    if n_interventions == 0:
        return (f"The controller's proposal was accepted without modification; "
               f"verified transformer loading settled at {tx_loading:.1f}%.")
    # Name the GROUPS that were actually throttled (scale < 1.0), not the
    # final state's constraint-violation TYPES -- those are near-certainly
    # empty here, because the whole point of an intervention is that the
    # final, reduced action is verified clean. Reporting the empty
    # violations list in this sentence (an earlier version of this function
    # did exactly that) would silently say "reduced one or more resource
    # groups" without ever naming one, even when `scales` knew exactly which
    # group and by how much.
    throttled = {g: s for g, s in scales.items() if s < 0.999}
    if throttled:
        parts = ', '.join(f"{g} to {s*100:.0f}% of requested" for g, s in sorted(throttled.items()))
        groups_txt = parts
    else:
        groups_txt = "one or more resource groups (exact group not resolved this step)"
    return (f"The safety layer reduced {groups_txt} to stay within electrical limits "
           f"({n_interventions} intervention(s) this step); verified transformer "
           f"loading settled at {tx_loading:.1f}%.")


def build_trace(k, t, obs, forecast, ev_p, prot, bc, bd, fl, res, pst,
                controller_name, fallback_used=False):
    """Build one DecisionTrace record. Raises ValueError if `res.status` is
    not one of the three required statuses -- see module docstring."""
    if res.status not in REQUIRED_STATUSES:
        raise ValueError(f"unknown safety status {res.status!r}; expected one of "
                        f"{REQUIRED_STATUSES} -- do not silently coerce this")

    net_p10 = float(forecast['inflex']['p10'][k] - forecast['pv']['p90'][k])
    net_p50 = float(forecast['inflex']['p50'][k] - forecast['pv']['p50'][k])
    net_p90 = float(forecast['inflex']['p90'][k] - forecast['pv']['p10'][k])

    tr = DecisionTrace(
        step=k, hour=round(obs['hour'], 2),
        detected=_detect(obs, forecast, k),
        forecast_p10_kw=round(net_p10, 1), forecast_p50_kw=round(net_p50, 1),
        forecast_p90_kw=round(net_p90, 1),
        actions=_summarise_actions(ev_p, prot, bc, bd, fl),
        safety_status=res.status.upper(),
        safety_interventions=int(res.n_interventions),
        safety_scales={g: round(float(s), 3) for g, s in res.scales.items()},
        violations=list(res.report.get('violations', [])),
        result_tx_loading_pct=round(float(pst['tx_loading']), 2) if pst.get('finite', True) else float('nan'),
        result_vmin_pu=round(float(pst['vmin']), 4) if pst.get('finite', True) else float('nan'),
        result_vmax_pu=round(float(pst['vmax']), 4) if pst.get('finite', True) else float('nan'),
        reason=_reason(res.status, res.n_interventions, res.scales,
                      pst.get('tx_loading', float('nan')), fallback_used),
        controller=controller_name,
    )
    return tr
