"""
rural.py -- Rural kit: shared solar, community battery, water storage + pumps, cold
store, shops, streetlights, a clinic and productive loads on a weak LV feeder.

ALL SIZES ARE RESEARCH ASSUMPTIONS (spec: 100 kWp solar, 20 kWh / 16 kW battery,
160 kWh-equivalent water storage, 50 kWh thermal, 100 streetlights, 3 pumps,
2 small industries), NOT a deployment quotation. No rural performance number is
authoritative until it has been regenerated by experiments.py and checked.

Arms (identical weather, loads, outage, initial states):
    naive  habitual pump/mill hours, thermostat cold store, self-consumption
           battery, equal-cut shedding, no physics check
    neos   priority tiers, deadline scheduler (min-run / min-rest / staggered
           starts), surplus router in the visible priority order, protected
           resilience reserve, physics projection on the weak-feeder twin

Surplus routing order (NEOS never invents surplus):
    1 local demand  2 battery charging  3 water pumping  4 thermal/cold storage
    5 productive shiftable work (mill)  6 export if feeder limits allow  7 curtail
Shed order under shortage: T5 discretionary, T4 flexible, T3 productive, T2 community, T1 critical last.

Islanding is a CONCEPT state machine (islanding.py), not field protection. Rooftop PV
is assumed NOT to ride through; the shared solar here is behind a grid-forming
converter in the concept design.
"""
from __future__ import annotations
from dataclasses import dataclass, asdict
import hashlib, json, math
import numpy as np

from .world import weather_ensemble, pv_power
from .grid import ReferenceGrid, constraint_report
from .control import safety_project, compose
from .resources import PumpRes, TankSystem, ColdStoreRes, ShiftableBlock, BatteryRes
from .islanding import IslandController, GRID, ISLANDED, SHUTDOWN, RESYNC
from .trace import DecisionTrace
from .reserve import FixedReserve, hours_remaining

DT = 0.25
T = 96
TIER_NAMES = {1: 'critical', 2: 'community', 3: 'productive', 4: 'flexible', 5: 'discretionary'}


@dataclass(frozen=True)
class RuralConfig:
    pv_kwp: float = 100.0
    batt_kwh: float = 20.0
    batt_kw: float = 16.0
    batt_soc_min: float = 0.10
    batt_soc_max: float = 0.95
    start_soc: float = 0.60
    tank_cap: float = 160.0
    tank_min: float = 30.0
    tank_start: float = 100.0
    water_kwh_per_day: float = 70.0
    n_pumps: int = 3
    pump_kw: float = 7.5
    cold_cap: float = 50.0
    cold_min: float = 10.0
    cold_start: float = 35.0
    cold_kw: float = 5.0
    n_lights: int = 100
    light_w: float = 30.0
    n_homes: int = 120
    clinic_kw: float = 1.5
    mill_kw: float = 15.0
    mill_kwh: float = 45.0
    workshop_kw: float = 5.0
    import_cap_kw: float = 60.0
    shave_target_kw: float = 30.0
    tx_kva: float = 100.0
    seg_km: float = 0.15
    z_scale: float = 1.5
    reserve: float = 0.40
    island_endurance_h: float = 4.0     # hours the non-critical tiers should be sustained
    critical_endurance_h: float = 6.0   # hours tier 1 is protected FIRST (a charter decision)

    def config_hash(self):
        return hashlib.sha256(json.dumps(asdict(self), sort_keys=True).encode()).hexdigest()[:16]


class RuralNet:
    """Minimal network description consumed by ReferenceGrid."""
    def __init__(self, n=8, seg_km=0.25):
        self.nodes = [(f"r{i}", 0, i * seg_km) for i in range(1, n + 1)]
        self.tx_kva = 100.0


def make_grid(cfg: RuralConfig):
    g = ReferenceGrid(RuralNet(8, cfg.seg_km), cfg.tx_kva)
    g.set_impedance_scale(cfg.z_scale)
    return g


def _gauss(x, m, s):
    return np.exp(-((x - m) / s) ** 2)


def profiles(cfg, rng, temp):
    h = np.arange(T) * DT
    p = {}
    p['clinic'] = np.full(T, cfg.clinic_kw)
    p['lights'] = np.where((h >= 18.5) | (h < 5.5), cfg.n_lights * cfg.light_w / 1000.0, 0.0)
    p['home_ess'] = cfg.n_homes * 0.06 * (1 + 0.4 * _gauss(h, 20, 2))
    p['shops'] = np.where((h >= 9) & (h < 20), 3.2, 0.3)
    p['workshop'] = np.where((h >= 9) & (h < 17), cfg.workshop_kw, 0.0)
    dd = cfg.n_homes * 0.10 * (0.4 + 0.8 * _gauss(h, 7, 1.2) + 1.6 * _gauss(h, 20, 2.2))
    p['home_disc'] = dd * rng.lognormal(0, 0.12, T)
    shape = 0.2 + _gauss(h, 7, 1.3) + 0.8 * _gauss(h, 18, 1.5)
    p['water'] = cfg.water_kwh_per_day * shape / shape.sum()          # kWh-eq per step
    return p


def simulate_day(cfg: RuralConfig, arm: str, seed=0, regime='normal', outage=None, reserve=None,
                 pv_fc_kt=0.85, physics=True, trace: DecisionTrace | None = None,
                 grid=None, mill_window=(32, 68)):
    """outage: None or (start_h, end_h). Returns metrics dict (and trace via argument)."""
    neos = arm == 'neos'
    rng = np.random.default_rng(seed)
    w = weather_ensemble(n_days=1, day_of_year=140, seed=seed, regime=regime)
    pv = pv_power(w['ghi'], w['temp'], cfg.pv_kwp)
    pv_fc = pv_power(w['ghi_cs'] * pv_fc_kt, w['temp'], cfg.pv_kwp)
    temp = w['temp']
    P = profiles(cfg, rng, temp)
    reserve = reserve or FixedReserve(cfg.reserve)
    grid = grid or (make_grid(cfg) if physics else None)
    isl = IslandController(soc_floor=cfg.batt_soc_min + 0.01, soc_restart=0.20, resync_min_steps=2)

    tank = TankSystem(cap=cfg.tank_cap, level=cfg.tank_start, minimum=cfg.tank_min)
    pumps = [PumpRes(f'P{i + 1}', 'pump', 4, node='r8', phase=0, p_kw=cfg.pump_kw, tank=tank)
             for i in range(cfg.n_pumps)]
    cold = ColdStoreRes('ColdStore', 'cold', 4, node='r4', phase=1, cap_th=cfg.cold_cap, s_th=cfg.cold_start,
                        s_min=cfg.cold_min, p_el_kw=cfg.cold_kw)
    mill = ShiftableBlock('Mill', 'mill', 4, node='r6', phase=0, p_kw=cfg.mill_kw, kwh_total=cfg.mill_kwh,
                          remaining_kwh=cfg.mill_kwh, win_start=mill_window[0], win_end=mill_window[1])
    batt = BatteryRes('Battery', 'battery', 3, node='r8', phase=0, cap_kwh=cfg.batt_kwh, p_max_kw=cfg.batt_kw,
                      e_kwh=cfg.start_soc * cfg.batt_kwh, eta=0.96, soc_min=cfg.batt_soc_min,
                      soc_max=cfg.batt_soc_max)
    e0_equiv = batt.e_kwh + tank.level + cold.s_th / cold.cop
    mill_start_naive = 68
    deadlines = [(24, 90.0), (68, 90.0)]
    out_steps = np.zeros(T, bool)
    if outage:
        out_steps[int(outage[0] / DT):int(outage[1] / DT)] = True

    names = ['clinic', 'lights', 'home_ess', 'shops', 'workshop', 'home_disc']
    tier_of = dict(clinic=1, lights=2, home_ess=2, shops=3, workshop=3, home_disc=5)
    dem = {k: 0.0 for k in ['t1', 't2', 't3', 't4', 't5']}
    dlv = {k: 0.0 for k in dem}
    m = dict(imp_kwh=0.0, exp_kwh=0.0, curt_kwh=0.0, pv_kwh=float(pv.sum() * DT), pv_used_kwh=0.0,
             peak_import=0.0, vmin=9.0, vmax=0.0, phase_load_max=0.0, line_max=0.0, steps_viol=0,
             steps_verified=0, steps_checked=0, interventions=0, ens_t12_out=0.0, h_no_crit=0.0,
             h_no_t12_out=0.0, tank_below_min_steps=0, cold_below_min_steps=0, batt_floor_hits=0,
             deadline_infeasible=0, pump_starts=0, shed_events=0, protect_overrides=0,
             batt_loss=0.0, shifted_kwh=0.0)
    deadline_ok = {}
    prev_tier_short = False
    shed_log = []

    def hr(t):
        return t * DT

    def add_inj(inj, kw, node, ph):
        if kw == 0:
            return
        if ph == 0:
            for q in (1, 2, 3):
                inj[(node, q)] = inj.get((node, q), 0.0) + kw / 3.0
        else:
            inj[(node, ph)] = inj.get((node, ph), 0.0) + kw

    for t in range(T):
        h = hr(t)
        grid_ok = not out_steps[t]
        for _ in range(3):
            info = isl.step(t, grid_ok, batt.soc)
            if isl.state in (GRID, ISLANDED, RESYNC, SHUTDOWN):
                break
        tie = isl.tie_closed
        shutdown = isl.state == SHUTDOWN
        islanded = not tie

        fixed = {k: float(P[k][t]) for k in names}
        for k in names:
            dem['t' + str(tier_of[k])] += fixed[k] * DT
        wdraw = float(P['water'][t])
        tank.level = max(0.0, tank.level - wdraw)
        cold.s_th = max(0.0, cold.s_th - cold.leak(temp[t]))
        pv_t = float(pv[t]) if (tie or islanded) else float(pv[t])
        if not tie and not neos:
            pass

        # ------------------------------------------------ flexible-load decisions
        for p in pumps:
            p.started_this_step = False
        commit = {}                 # name -> kW already committed (min-run) this step
        for p in pumps:
            lo, hi = p.limits()
            if p.on and lo > 0:
                commit[p.name] = lo
        if cold.on:
            lo, hi = cold.limits()
            if lo > 0:
                commit[cold.name] = lo
        if mill.running:
            lo, hi = mill.limits()
            commit[mill.name] = lo

        want = dict(commit)       # name -> kW wanted
        must = set(commit)        # names that are not sheddable by choice
        why = {}

        if neos:
            # ---- pump deadline logic
            nxt = next(((d, tg) for d, tg in deadlines if d > t), None)
            need, slack, dl = 0.0, 99, None
            if nxt:
                dl, tg = nxt
                L_proj = tank.level - float(P['water'][t + 1:dl].sum())
                need = max(0.0, tg - L_proj)
                rate = cfg.n_pumps * cfg.pump_kw * DT
                steps_needed = math.ceil(need / rate - 1e-9) + 2 if need > 0 else 0
                slack = (dl - t) - steps_needed
                if need > rate * (dl - t) + 1e-9 and (dl, 'inf') not in deadline_ok:
                    deadline_ok[(dl, 'inf')] = True
                    m['deadline_infeasible'] += 1
                    if trace:
                        trace.add(t, h, f'deadline {int(dl * DT):02d}:00 infeasible for water',
                                  f'need {need:.0f} kWh-eq but pumps can lift at most {rate * (dl - t):.0f}',
                                  resource='pumps', binding=['pump power x time to deadline'],
                                  physics='not_checked', kind='protect', expected='report INFEASIBLE, run all pumps',
                                  actual='best-effort')
            emergency = tank.level < tank.minimum + 10
            pressure = (need > 0 and slack <= 0) or emergency
            n_run_needed = 0
            if pressure:
                n_run_needed = cfg.n_pumps if emergency or need > 0.7 * cfg.n_pumps * cfg.pump_kw * DT * max(1, (dl or t + 1) - t) else \
                    max(1, math.ceil(need / (cfg.pump_kw * DT * max(1, (dl or t + 4) - t - 1))))
            running = [p for p in pumps if p.name in commit]
            starts = 0
            for p in pumps:
                if p.name in commit:
                    continue
                if len(running) + starts >= n_run_needed:
                    break
                if p.can_start() and starts == 0:                  # staggered: one start per step
                    want[p.name] = cfg.pump_kw; must.add(p.name); starts += 1
                    why[p.name] = (f'deadline pressure: need {need:.0f} kWh-eq by {(dl or 0) * DT:.0f}:00, '
                                   f'slack {slack} steps' if not emergency else f'tank {tank.level:.0f} < min+10')
            # ---- mill must-run on window pressure
            ds = mill.deadline_status(t)
            if (not mill.running) and mill.remaining_kwh > 1e-9 and mill.win_start <= t < mill.win_end \
                    and ds['steps_left'] - ds['need_steps'] <= 1:
                want[mill.name] = cfg.mill_kw; must.add(mill.name)
                why[mill.name] = f'window closes in {ds["steps_left"]} steps, needs {ds["need_steps"]}'
            # ---- cold store protective run
            if cold.s_th < cold.s_min + 6 and not cold.on:
                want[cold.name] = cfg.cold_kw; must.add(cold.name); why[cold.name] = 'cooling store approaching its hard minimum'
        else:
            for p in pumps:
                if p.name in commit:
                    continue
                if (5.0 <= h < 8.0 or 16.5 <= h < 19.5) and p.can_start():
                    want[p.name] = cfg.pump_kw                      # all start together (no stagger)
            if t == mill_start_naive and not mill.running and mill.remaining_kwh > 1e-9:
                want[mill.name] = cfg.mill_kw
            if (not cold.on and cold.s_th < 25) or (cold.on and cold.s_th < 45):
                want[cold.name] = cfg.cold_kw
            must = set(want)

        # ------------------------------------------------ supply / power balance
        served = {k: 1.0 for k in names}
        flex_scale = {k: 1.0 for k in want}
        service_level = 5
        if neos and islanded and not shutdown:
            # ENDURANCE-BASED SERVICE LEVEL: serve the highest tier set whose net load the
            # battery can sustain for island_endurance_h; tier 1 is always attempted.
            t1 = fixed['clinic']; t2 = fixed['lights'] + fixed['home_ess']
            t3 = fixed['shops'] + fixed['workshop'] + sum(kw for n_, kw in want.items() if n_ in must)
            t4o = sum(kw for n_, kw in want.items() if n_ not in must)
            cum = {1: t1, 2: t1 + t2, 3: t1 + t2 + t3, 4: t1 + t2 + t3 + t4o, 5: t1 + t2 + t3 + t4o + fixed['home_disc']}
            e_ac = max(0.0, batt.e_kwh - cfg.batt_soc_min * batt.cap_kwh) * batt.eta
            spare = max(0.0, e_ac - t1 * cfg.critical_endurance_h)       # energy left after securing tier 1
            for L_ in (5, 4, 3, 2, 1):
                others = max(0.0, cum[L_] - t1 - float(pv[t]))
                if L_ == 1 or others <= 1e-9 or spare / others >= cfg.island_endurance_h:
                    service_level = L_
                    break
            # marginal tier gets a FRACTIONAL fair share of the endurance headroom left after
            # the higher tiers are secured for the target duration (no stranded energy)
            comp = {1: [('f', 'clinic')], 2: [('f', 'lights'), ('f', 'home_ess')],
                    3: [('f', 'shops'), ('f', 'workshop')] + [('x', n_) for n_ in want if n_ in must],
                    4: [('x', n_) for n_ in want if n_ not in must], 5: [('f', 'home_disc')]}
            kwc = lambda c: fixed[c[1]] if c[0] == 'f' else want[c[1]]
            frac_next = 0.0
            if service_level < 5:
                nxt_t = service_level + 1
                tier_kw = sum(kwc(c) for c in comp[nxt_t])
                extra = spare / cfg.island_endurance_h - max(0.0, cum[service_level] - t1 - float(pv[t]))
                frac_next = 0.0 if tier_kw <= 1e-9 else float(min(1.0, max(0.0, extra / tier_kw)))
            for tier_, items in comp.items():
                f_ = 1.0 if tier_ <= service_level else (frac_next if tier_ == service_level + 1 else 0.0)
                for c in items:
                    if c[0] == 'f':
                        served[c[1]] = f_
                    else:
                        flex_scale[c[1]] = f_
            if trace and service_level < 5 and (t == 0 or getattr(trace, '_lvl', 5) != service_level):
                trace.add(t, h, f'island service level -> tier <= {service_level}',
                          f'battery {batt.soc * 100:.0f} % secures tier 1 for {cfg.critical_endurance_h:.0f} h and sustains tier <= {service_level} for {cfg.island_endurance_h:.0f} h',
                          binding=[f'tier-1 endurance {cfg.critical_endurance_h:.0f} h', f'others {cfg.island_endurance_h:.0f} h', 'battery energy'],
                          reserve_protected=f'battery floor {cfg.batt_soc_min * 100:.0f} %',
                          physics='not_modelled', kind='shed', expected='critical load served for the target duration',
                          actual='see tier delivery')
            if trace:
                trace._lvl = service_level
        fixed_kw = sum(fixed[k] * served[k] for k in names)
        flex_kw = sum(kw * flex_scale.get(n_, 1.0) for n_, kw in want.items())
        supply_pv = pv_t
        residual = supply_pv - fixed_kw - flex_kw
        batt_cmd = 0.0                       # +discharge, -charge
        imp = exp = curt = 0.0
        b_lo, b_hi = batt.limits()
        floor_soc = (cfg.batt_soc_min if (islanded or not neos) else max(cfg.batt_soc_min, reserve.value()))

        def batt_dis_allowed():
            cap = batt.cap_kwh
            e_floor = floor_soc * cap
            return min(b_hi, max(0.0, batt.e_kwh - e_floor) * batt.eta / DT)

        if shutdown:
            # island has no energy: nothing is served this step
            served = {k: 0.0 for k in names}
            flex_scale = {k: 0.0 for k in want}
            residual = 0.0
            curt = max(0.0, pv_t)
        elif residual >= 0:
            surplus = residual
            ch = min(-b_lo, surplus) if (batt.soc < cfg.batt_soc_max) else 0.0
            batt_cmd = -ch; surplus -= ch
            if neos:
                # 3 pumps  4 thermal  5 productive work, in the visible order
                for p in pumps:
                    if p.name in want or not p.can_start() or tank.level > tank.cap - 0.35 * cfg.pump_kw:
                        continue
                    if surplus >= cfg.pump_kw and not any(x.started_this_step for x in pumps):
                        want[p.name] = cfg.pump_kw; flex_scale[p.name] = 1.0; surplus -= cfg.pump_kw
                        p.started_this_step = True
                        why[p.name] = f'surplus solar {surplus + cfg.pump_kw:.1f} kW available (router step 3: water pumping)'
                if cold.name not in want and cold.s_th < cold.cap_th - 2 and surplus >= cfg.cold_kw and not (18 <= h < 22):
                    want[cold.name] = cfg.cold_kw; flex_scale[cold.name] = 1.0; surplus -= cfg.cold_kw
                    why[cold.name] = 'surplus solar: pre-cool (router step 4: thermal storage)'
                if mill.name not in want and mill.remaining_kwh > 1e-9 and mill.win_start <= t < mill.win_end \
                        and surplus >= cfg.mill_kw and mill.deadline_status(t)['steps_left'] >= mill.steps_left_needed():
                    want[mill.name] = cfg.mill_kw; flex_scale[mill.name] = 1.0; surplus -= cfg.mill_kw
                    why[mill.name] = 'surplus solar covers the full block (router step 5: productive work)'
            if tie:
                e_lim = 0.0 if grid is None else 1e9
                exp = surplus if surplus > 0 else 0.0     # export attempted; physics may clip below
            else:
                curt = surplus
            if not tie:
                exp = 0.0
        else:
            D = -residual
            # shortage: battery first (neos: only above reserve unless islanded/peak), then grid, then shed
            dis_ok = batt_dis_allowed() if (islanded or not neos) else 0.0
            if neos and tie:
                total_import_pre = D
                if total_import_pre > cfg.shave_target_kw:
                    dis_ok = min(batt_dis_allowed(), total_import_pre - cfg.shave_target_kw)
                else:
                    dis_ok = 0.0
            elif not neos and tie:
                dis_ok = min(b_hi, max(0.0, batt.e_kwh - cfg.batt_soc_min * batt.cap_kwh) * batt.eta / DT)
            use_b = min(D, dis_ok); D -= use_b; batt_cmd = use_b
            if tie:
                imp = min(D, cfg.import_cap_kw); D -= imp
                if neos and not shutdown and batt_cmd >= 0 and D <= 1e-9:
                    # protect the resilience reserve: top the battery up from the grid
                    need_e = max(0.0, reserve.value() * batt.cap_kwh - batt.e_kwh)
                    if need_e > 1e-9:
                        add = max(0.0, min(-b_lo, need_e / (batt.eta * DT), cfg.import_cap_kw - imp))
                        if add > 1e-9:
                            batt_cmd = -add; imp += add
            # remaining D must be shed
            if D > 1e-9:
                m['shed_events'] += 1
                order = []
                if neos:
                    # reverse tier order. Flexible loads first (unless must), then T5.. T1
                    order = [(k, 5) for k in ['home_disc']]
                    order += [(n, 4) for n in list(want) if n not in must]
                    order += [(n, 4) for n in list(want) if n in must]
                    order += [(k, 3) for k in ['shops', 'workshop']] + [(k, 2) for k in ['lights', 'home_ess']] + [('clinic', 1)]
                    for name, tr_ in order:
                        if D <= 1e-9:
                            break
                        if name in fixed:
                            cut = min(fixed[name] * served[name], D); served[name] -= cut / max(fixed[name], 1e-9); D -= cut
                        else:
                            cut = min(want[name] * flex_scale.get(name, 1.0), D)
                            flex_scale[name] = flex_scale.get(name, 1.0) - cut / want[name]; D -= cut
                    if trace and tier_short_msg(served, flex_scale, want, fixed):
                        trace.add(t, h, 'shed lower tiers to protect critical service',
                                  f'shortfall: PV {pv_t:.1f} kW + battery {use_b:.1f} kW + import {imp:.1f} kW < demand',
                                  binding=['supply' if islanded else f'import cap {cfg.import_cap_kw:.0f} kW'],
                                  reserve_protected=f'battery floor {floor_soc * 100:.0f} %' if neos else '',
                                  physics='not_modelled' if islanded else 'PASS', kind='shed',
                                  expected='tier 1-2 served', actual='see tier delivery')
                else:
                    total = sum(fixed.values()) + sum(want.values())
                    f = max(0.0, 1 - D / max(total, 1e-9))                 # equal cut, tier-blind
                    served = {k: f for k in names}
                    flex_scale = {k: f for k in want}
                    D = 0.0
        # -------------------------------------------------- physics (grid-connected steps)
        phys = 'not_modelled'
        if physics and grid is not None and tie and not shutdown:
            inj_base = {}
            # households and lights are spread over many services/phases; shops, workshop,
            # clinic and cold store are single-phase services (mild, realistic imbalance)
            spread_nodes = ['r3', 'r4', 'r5', 'r6', 'r7']
            for k in names:
                kw_k = fixed[k] * served[k]
                if k in ('home_ess', 'home_disc', 'lights'):
                    for nd_ in spread_nodes:
                        add_inj(inj_base, kw_k / len(spread_nodes), nd_, 0)
                else:
                    nd, ph_ = {'clinic': ('r2', 1), 'shops': ('r4', 2), 'workshop': ('r5', 3)}[k]
                    add_inj(inj_base, kw_k, nd, ph_)
            groups = {'appl': {}, 'batt_chg': {}, 'batt_dis': {}}
            res_by = {p.name: p for p in pumps}; res_by[cold.name] = cold; res_by[mill.name] = mill
            for n_, kw_ in want.items():
                r_ = res_by[n_]
                add_inj(groups['appl'], kw_ * flex_scale.get(n_, 1.0), r_.node, r_.phase)
            if batt_cmd < 0:
                add_inj(groups['batt_chg'], -batt_cmd, 'r8', 0)
            elif batt_cmd > 0:
                add_inj(groups['batt_dis'], -batt_cmd, 'r8', 0)
            pv_inj = {}
            net_pv = pv_t - curt
            add_inj(pv_inj, -net_pv, 'r8', 0)
            if neos:
                sp = safety_project(grid, inj_base, pv_inj, groups, limits=None)
                st, scales, pvs = sp.state, sp.scales, sp.pv_scale
                m['steps_checked'] += 1
                m['steps_verified'] += sp.status == 'verified'
                if sp.n_interventions or pvs < 1:
                    m['interventions'] += 1
                    if scales.get('appl', 1) < 1:
                        for n_ in want:
                            if n_ not in must:
                                flex_scale[n_] *= scales['appl']
                            else:
                                flex_scale[n_] *= scales['appl']; m['protect_overrides'] += 1
                    if scales.get('batt_chg', 1) < 1 and batt_cmd < 0:
                        batt_cmd *= scales['batt_chg']
                    if scales.get('batt_dis', 1) < 1 and batt_cmd > 0:
                        batt_cmd *= scales['batt_dis']
                    if pvs < 1:
                        curt += (1 - pvs) * net_pv
                    if trace:
                        trace.add(t, h, 'physics layer reduced the proposal', 'AC check found ' + ', '.join(sp.report['violations'] or ['violation']),
                                  binding=sp.report['violations'], physics=f'FAIL then {sp.status}', kind='protect',
                                  expected='dispatch within voltage/ampacity/phase limits',
                                  actual=f"scales={ {k: round(v, 2) for k, v in scales.items()} }, pv_scale={pvs:.2f}")
                phys = sp.status
            else:
                # naive arm: loads are NOT controllable, but the PV inverter still has basic local
                # over-voltage protection (same baseline strength as the urban uncoordinated arm)
                base_all = compose(inj_base, {}, groups, {g: 1.0 for g in groups}, 1.0)
                sp = safety_project(grid, base_all, pv_inj, {}, limits=None)
                st = sp.state
                if sp.pv_scale < 1.0:
                    curt += (1 - sp.pv_scale) * net_pv
                m['steps_checked'] += 1
                m['steps_verified'] += sp.status == 'verified'
                phys = 'PASS' if sp.status == 'verified' else sp.status.upper() + ':' + ','.join(sp.report['violations'])
            if st['finite']:
                m['vmin'] = min(m['vmin'], st['vmin']); m['vmax'] = max(m['vmax'], st['vmax'])
                m['phase_load_max'] = max(m['phase_load_max'], st.get('phase_loading_max', 0.0))
                m['line_max'] = max(m['line_max'], st['line_loading_max'])
                m['steps_viol'] += sp.status != 'verified'
                imp_phys = max(st['tx_kw'], 0.0)
                exp = max(-st['tx_kw'], 0.0)
                imp = imp_phys

        # -------------------------------------------------- apply to resource state
        if batt_cmd != 0 and (shutdown is False):
            lo_, hi_ = batt.limits()
            batt_cmd = min(max(batt_cmd, lo_), hi_)
            e_before = batt.e_kwh
            batt._apply(batt_cmd, DT)
            m['batt_loss'] += abs(batt_cmd) * DT * (1 - batt.eta) if batt_cmd < 0 else abs(batt_cmd) * DT * (1 / batt.eta - 1)
        elif shutdown:
            pass
        for n_, kw_ in want.items():
            r_ = ({p.name: p for p in pumps} | {cold.name: cold, mill.name: mill})[n_]
            p_act = kw_ * flex_scale.get(n_, 1.0)
            if p_act < 0.05:
                p_act = 0.0
            if isinstance(r_, PumpRes) and p_act > 0 and not r_.on:
                m['pump_starts'] += 1
                if trace:
                    trace.add(t, h, f'start {r_.name} ({p_act:.1f} kW)', why.get(n_, 'habitual schedule' if not neos else 'scheduler'),
                              resource=r_.name, forecast={'pv_p50_kw': round(float(pv_fc[t]), 1)},
                              binding=['one pump start per step', f'min run {r_.min_run * 15} min'],
                              reserve_protected=f'battery floor {floor_soc * 100:.0f} %',
                              physics=phys, kind='dispatch', expected=f'tank +{p_act * DT:.1f} kWh-eq / step',
                              actual='see tank level')
            if isinstance(r_, ShiftableBlock) and p_act > 0 and not r_.running and trace:
                trace.add(t, h, f'start {r_.name} ({p_act:.0f} kW block)', why.get(n_, 'habitual evening start'),
                          resource=r_.name, binding=['non-interruptible block', f'window {mill.win_start * DT:.0f}:00-{mill.win_end * DT:.0f}:00'],
                          physics=phys, kind='dispatch', expected=f'{mill.remaining_kwh:.0f} kWh of work', actual='see completion')
            if isinstance(r_, PumpRes):
                r_.apply(p_act) if (lambda lo, hi: lo - 1e-9 <= p_act <= hi + 1e-9)(*r_.limits()) else r_._apply(p_act, DT)
            elif isinstance(r_, ColdStoreRes):
                r_.apply(p_act) if (lambda lo, hi: lo - 1e-9 <= p_act <= hi + 1e-9)(*r_.limits()) else r_._apply(p_act, DT)
            else:
                r_.apply(p_act) if (lambda lo, hi: lo - 1e-9 <= p_act <= hi + 1e-9)(*r_.limits()) else r_._apply(p_act, DT)
        for p in pumps:
            if p.name not in want:
                p._apply(0.0, DT)
        if cold.name not in want:
            cold._apply(0.0, DT)
        if mill.name not in want and mill.running:
            mill.running = False
        # -------------------------------------------------- accounting
        for k in names:
            dlv['t' + str(tier_of[k])] += fixed[k] * served[k] * DT
        flex_el = sum(kw * flex_scale.get(n_, 1.0) for n_, kw in want.items())
        dem['t4'] += sum(commit.values()) * 0 + 0.0
        dlv['t4'] += flex_el * DT
        used_pv = min(pv_t - curt, fixed_kw + flex_el + max(-batt_cmd, 0))
        m['pv_used_kwh'] += max(0.0, used_pv) * DT
        m['imp_kwh'] += imp * DT; m['exp_kwh'] += exp * DT; m['curt_kwh'] += curt * DT
        m['peak_import'] = max(m['peak_import'], imp)
        if neos and h > 5:
            reserve.update(float(pv_fc[t]) if pv_fc[t] > 1 else 0.0, float(pv[t]) if pv_fc[t] > 1 else 0.0)
        if out_steps[t]:
            crit = served['clinic'] if not shutdown else 0.0
            t12 = fixed['lights'] * served['lights'] + fixed['home_ess'] * served['home_ess']
            t12need = fixed['lights'] + fixed['home_ess']
            m['ens_t12_out'] += (t12need - t12) * DT + (fixed['clinic'] * (1 - crit)) * DT
            if crit < 0.999:
                m['h_no_crit'] += DT
            if t12 < t12need - 1e-6 or crit < 0.999:
                m['h_no_t12_out'] += DT
        if tank.level < tank.minimum:
            m['tank_below_min_steps'] += 1
        if cold.s_th < cold.s_min:
            m['cold_below_min_steps'] += 1
        for dl_, tg_ in deadlines:
            if t == dl_:
                deadline_ok[dl_] = tank.level >= tg_ - 1e-6
    # T4 demand: energy the flexible loads actually needed (pumps' share of water + mill + cold keep-up)
    dem['t4'] = cfg.water_kwh_per_day + cfg.mill_kwh
    water_lifted = min(cfg.water_kwh_per_day, max(0.0, (tank.level - cfg.tank_start) + cfg.water_kwh_per_day))
    mill_done = cfg.mill_kwh - mill.remaining_kwh
    dlv['t4'] = water_lifted + mill_done
    pump_dl = [bool(deadline_ok.get(d, False)) for d, _ in deadlines]
    e_end_equiv = batt.e_kwh + tank.level + cold.s_th / cold.cop
    out = dict(
        arm=arm, regime=regime, seed=seed, outage=outage, config_hash=cfg.config_hash(),
        tier_demand_kwh={TIER_NAMES[int(k[1])]: v for k, v in dem.items()},
        tier_delivery={TIER_NAMES[int(k[1])]: (dlv[k] / dem[k] if dem[k] > 1e-9 else 1.0) for k in dem},
        pump_deadlines_met=pump_dl, pump_deadline_satisfaction=float(np.mean(pump_dl)),
        pump_deadline_infeasible_flags=m['deadline_infeasible'],
        tank_final=tank.level, tank_below_min_hours=m['tank_below_min_steps'] * DT,
        cold_final=cold.s_th, cold_below_min_hours=m['cold_below_min_steps'] * DT,
        mill_completed=mill.remaining_kwh <= 1e-6, mill_remaining_kwh=mill.remaining_kwh,
        battery_final_soc=batt.soc,
        renewable_utilisation=m['pv_used_kwh'] / max(m['pv_kwh'], 1e-9) if m['pv_kwh'] > 0 else 0.0,
        pv_kwh=m['pv_kwh'], curtailed_kwh=m['curt_kwh'], export_kwh=m['exp_kwh'], import_kwh=m['imp_kwh'],
        peak_import_kw=m['peak_import'], v_min=m['vmin'] if m['vmin'] < 9 else None, v_max=m['vmax'] or None,
        phase_loading_max_pct=m['phase_load_max'], line_loading_max_pct=m['line_max'],
        physics_steps_checked=m['steps_checked'],
        physics_verified_pct=100.0 * m['steps_verified'] / max(1, m['steps_checked']),
        physics_violation_steps=int(m['steps_viol']), physics_interventions=m['interventions'],
        protection_overrides_of_must_run=m['protect_overrides'],
        outage_hours=float(out_steps.sum() * DT), essential_ens_outage_kwh=m['ens_t12_out'],
        hours_without_critical_outage=m['h_no_crit'], hours_without_t1t2_outage=m['h_no_t12_out'],
        shed_events=m['shed_events'], pump_starts=m['pump_starts'],
        battery_loss_kwh=m['batt_loss'], net_grid_energy_kwh=m['imp_kwh'] - m['exp_kwh'],
        net_grid_energy_storage_adjusted_kwh=(m['imp_kwh'] - m['exp_kwh']) - (e_end_equiv - e0_equiv),
        terminal_stored_equiv_kwh=e_end_equiv, initial_stored_equiv_kwh=e0_equiv,
        reserve_end=reserve.value(), reserve_policy=getattr(reserve, 'name', 'fixed'),
        island_log=isl.log[:12],
    )
    return out


def tier_short_msg(served, flex_scale, want, fixed):
    return any(v < 0.999 for v in served.values()) or any(v < 0.999 for v in flex_scale.values())
